version: '3.1'

services:
  payara:
    build: ../images/payara
    environment:
      - ADMIN_PASSWORD=adminadmin
    ports:
      - '8080:8080'
      - '4848:4848'
      - '9009:9009'
      - '8181:8181'
    # Link mysql container in the container payara when we use the host "db"
    links:
      - mysql:db

  mysql:
    image: mysql:latest
    restart: always
    #for v8 mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=""
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - ../images/mysql/db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '6060:80'
    links:
      - mysql:db
